# Generated by Django 6.0.5 on 2026-06-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de YouTube o enlace directo a video'),
        ),
    ]
