# Generated by Django 5.2.15 on 2026-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='tipo',
            field=models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], default='pelicula', max_length=10, verbose_name='Tipo'),
        ),
    ]
