# Generated by Django 6.0.6 on 2026-06-21 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_historialvisualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.PositiveIntegerField(default=1)),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('imagen', models.URLField(blank=True)),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
                ('serie', models.ForeignKey(limit_choices_to={'tipo': 'serie'}, on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='peliculas.pelicula')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['temporada', 'numero'],
                'unique_together': {('serie', 'temporada', 'numero')},
            },
        ),
    ]
