# Generated by Django 6.0.6 on 2026-06-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_capitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
    ]
